# Site settings
title: "Spellbook"
author: "Arne"
description:
  "A searchable D&D 5e spell list, sorted by class and level."
baseurl: "/spellbook" # the subpath of your site, e.g. /blog/
url: "http://testingtestsaregreat.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/testingtestsaregreat/spellbook/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
